---
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: centos:7
provisioner:
  name: ansible
  config_options:
    diff:
      always: true
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
    options:
      config-file: ${MOLECULE_PROJECT_DIRECTORY}/molecule/default/yaml-lint.yml
