---
extends: default

ignore: |
  test_*.yml
rules:
  braces:
    max-spaces-inside: 1
    level: warning
  brackets:
    max-spaces-inside: 1
    level: warning
  line-length:
    max: 200
    level: warning
  truthy: disable
